
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board
    driver-class-name: org.mariadb.jdbc.Driver
    username: application
    password: application
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true